Repository aviarytech/wacinsteins-monster, pull requests merged in 2021-09, with the labels that each got.

#49 Create openshift.md
  backend/openshift/build.yaml
  backend/openshift/db-image.yaml
  backend/openshift/db-template.yaml
  backend/openshift/deploy-db.sh
  backend/openshift/deploy-wacinstein.sh
  backend/openshift/image.yaml
  backend/openshift/openshift.md
  backend/openshift/params/aviary.id.params
  backend/openshift/params/aviary.one.params
  backend/openshift/params/aviary.vc.params
  backend/openshift/params/mongo.params
  backend/openshift/template.yaml
  backend/src/db/db.service.ts
Labels: review

#47 Henri/issue 38/messages UI
  backend/src/contacts/contacts.controller.ts
  backend/src/contacts/contacts.service.ts
  backend/src/db/db.service.ts
  frontend/src/App.svelte
  frontend/src/api/contactsAxios.ts
  frontend/src/interfaces.ts
  frontend/src/lib/Button.svelte
  frontend/src/lib/ChatMessage.svelte
  frontend/src/lib/DataTableRow.svelte
  frontend/src/lib/Image.svelte
  frontend/src/lib/Messenger.svelte
  frontend/src/lib/NewContacts.svelte
  frontend/src/lib/Text.svelte
  frontend/src/routes/Contacts.svelte
  frontend/src/routes/Messages.svelte
  frontend/src/stores/contacts.ts
  frontend/src/stores/messages.ts
  frontend/src/stores/routes.ts
Labels: enhancement, review

#52 Henri/issue 42/messages api
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/credentials/credentials.controller.ts
  backend/src/messages-api/dto/create-messages-api.dto.ts
  backend/src/messages-api/entities/messages-api.entity.ts
  backend/src/messages-api/interfaces/message-api.interface.ts
  backend/src/messages-api/messages-api.controller.spec.ts
  backend/src/messages-api/messages-api.controller.ts
  backend/src/messages-api/messages-api.module.ts
  backend/src/messages-api/messages-api.service.spec.ts
  backend/src/messages-api/messages-api.service.ts
  backend/src/presentations/presentations.controller.ts
  frontend/src/api/contactsAxios.ts
  frontend/src/api/messagesLogic.ts
  frontend/src/lib/ChatMessage.svelte
  frontend/src/lib/ContactProfile.svelte
  frontend/src/lib/DataTable.svelte
  frontend/src/lib/DataTableRow.svelte
  frontend/src/lib/Messenger.svelte
  frontend/src/lib/Navbar.svelte
  frontend/src/routes/Contacts.svelte
  frontend/src/routes/Messages.svelte
  frontend/src/routes/Presentations.svelte
  frontend/src/stores/messages.ts
Labels: enhancement, review

#58 started work on the integration of QR codes
  frontend/package.json
  frontend/src/lib/QRcode.svelte
  frontend/src/routes/Presentations.svelte
  frontend/src/stores/presentation.ts
  package.json
Labels: enhancement, review

#63 General ui improvements
  frontend/src/lib/ChatMessage.svelte
  frontend/src/lib/Messenger.svelte
  frontend/src/lib/QRcode.svelte
Labels: css

#73 QRCode now displays the url and adjusted the logo location.
  frontend/package.json
  frontend/src/lib/QRcode.svelte
  frontend/src/lib/ui/Button.svelte
  frontend/src/routes/Presentations.svelte
Labels: enhancement, review

#75 backend webscoket backbone in place
  backend/package.json
  backend/src/app.module.ts
  backend/src/messages-api-websocket/msg.gateway.ts
  backend/src/messages-api-websocket/msg.module.ts
  frontend/package.json
  frontend/src/lib/Messenger.svelte
  frontend/src/routes/Contacts.svelte
  frontend/src/routes/Messages.svelte
Labels: enhancement, review

#81 enhanced the componenet tag.svelte and added a col in presentation fo…
  frontend/src/lib/ui/Tag.svelte
  frontend/src/routes/Presentations.svelte
Labels: enhancement, review, css

#83 removed the <a> tag in the sidebar and instead made a button with an …
  frontend/src/lib/Sidebar.svelte
  frontend/src/routes/Home.svelte
Labels: enhancement, css

#82 I have a working decoder
  backend/src/didcomm/didcomm.controller.ts
  backend/src/didcomm/didcomm.service.ts
  backend/src/presentations/dto/accept-invitation.dto.ts
  backend/src/presentations/presentations.controller.ts
  backend/src/presentations/presentations.module.ts
  backend/src/presentations/presentations.service.ts
  frontend/src/api/presentationAxios.ts
  frontend/src/lib/QRcode.svelte
  frontend/src/lib/slideOverComponents/acceptInvitation.svelte
  frontend/src/routes/Presentations.svelte
Labels: enhancement, review

#88 CSS work done by the junior
  frontend/src/App.svelte
  frontend/src/lib/ContactProfile.svelte
  frontend/src/lib/Messenger.svelte
  frontend/src/lib/slideOverComponents/acceptInvitation.svelte
  frontend/src/lib/table-elements/DataTable.svelte
  frontend/src/lib/ui/SlideOver.svelte
  frontend/src/routes/Contacts.svelte
  frontend/src/routes/Messages.svelte
  frontend/src/routes/Presentations.svelte
  frontend/tailwind.config.cjs
Labels: css

#104 Henri/tests
  frontend/cypress.json
  frontend/package.json
  frontend/src/App.svelte
  frontend/src/lib/Router.svelte
  frontend/src/routes/DemoAuth.svelte
  tests/.gitignore
  tests/cypress.json
  tests/cypress/fixtures/example.json
  tests/cypress/fixtures/profile.json
  tests/cypress/fixtures/users.json
  tests/cypress/integration/examples/1-getting-started/todo.spec.js
  tests/cypress/integration/examples/2-advanced-examples/actions.spec.js
  tests/cypress/integration/examples/2-advanced-examples/aliasing.spec.js
  tests/cypress/integration/examples/2-advanced-examples/assertions.spec.js
  tests/cypress/integration/examples/2-advanced-examples/connectors.spec.js
  tests/cypress/integration/examples/2-advanced-examples/cookies.spec.js
  tests/cypress/integration/examples/2-advanced-examples/cypress_api.spec.js
  tests/cypress/integration/examples/2-advanced-examples/files.spec.js
  tests/cypress/integration/examples/2-advanced-examples/local_storage.spec.js
  tests/cypress/integration/examples/2-advanced-examples/location.spec.js
  tests/cypress/integration/examples/2-advanced-examples/misc.spec.js
  tests/cypress/integration/examples/2-advanced-examples/navigation.spec.js
  tests/cypress/integration/examples/2-advanced-examples/network_requests.spec.js
  tests/cypress/integration/examples/2-advanced-examples/querying.spec.js
  tests/cypress/integration/examples/2-advanced-examples/spies_stubs_clocks.spec.js
  tests/cypress/integration/examples/2-advanced-examples/traversal.spec.js
  tests/cypress/integration/examples/2-advanced-examples/utilities.spec.js
  tests/cypress/integration/examples/2-advanced-examples/viewport.spec.js
  tests/cypress/integration/examples/2-advanced-examples/waiting.spec.js
  tests/cypress/integration/examples/2-advanced-examples/window.spec.js
  tests/cypress/integration/examples/credentialPage.spec.js
  tests/cypress/integration/examples/presentationSchemaBuilder.spec.js
  tests/cypress/integration/examples/sidebar.spec.js
  tests/cypress/integration/examples/test.spec.js
  tests/cypress/integration/waci-pex/createPresentationRequest.spec.js
  tests/cypress/plugins/index.ts
  tests/cypress/support/commands.js
  tests/cypress/support/index.js
  tests/package.json
Labels: frontend, backend

#108 camera starts and stop and we do not have anymore component breaking error
  frontend/package.json
  frontend/public/assets/svg/outlineCamera.svg
  frontend/src/lib/CameraReader.svelte
  frontend/src/routes/Presentations.svelte
  frontend/src/stores/presentation.ts
Labels: css, frontend

#113 mobile sidebar
  frontend/src/App.svelte
  frontend/src/lib/Sidebar.svelte
  frontend/src/lib/ui/SlideOver.svelte
  frontend/src/stores/ui.ts
Labels: css, frontend

#114 Henri/camera modal
  frontend/package.json
  frontend/src/lib/Router.svelte
  frontend/src/lib/Sidebar.svelte
  frontend/src/lib/slideOverItems/QRcode.svelte
  frontend/src/routes/Presentations.svelte
Labels: css, frontend

#123 issue-122 was chain-smoked off issue #91/pr#120 which is not ready. c…
  frontend/src/lib/Sidebar.svelte
  frontend/src/stores/ui.ts
Labels: bug, css, frontend

#117 Henri/cypress actions
  .github/workflows/frontend-cy-tests.yml
  tests/cypress/integration/waci-pex.spec.js
Labels: enhancement, tests

#124 fixed the double typing issue. tested by entering a new entry and typ…
  frontend/src/routes/Messages.svelte
Labels: bug, enhancement, frontend

#129 cleaned the breaks and added the changed done by Brian on the QrCode.
  frontend/src/lib/slideOverItems/PresentationDetailedView.svelte
  frontend/src/lib/slideOverItems/QRcode.svelte
  frontend/src/lib/slideOverItems/SchemaBuilder.svelte
  frontend/src/routes/Identities.svelte
  frontend/src/routes/Presentations.svelte
  frontend/src/stores/presentation.ts
Labels: frontend, refactor

#130 Henri/issue 126/xpub implementation
  frontend/package.json
  frontend/src/lib/slideOverItems/QRcode.svelte
  frontend/src/routes/Identities.svelte
  frontend/src/routes/Presentations.svelte
  frontend/src/stores/identities.ts
  frontend/src/stores/xpub.ts
  frontend/src/utils/tailwind.ts
Labels: enhancement, frontend

#133 Update README.md
  README.md
Labels: css

#139 removed the regrexs and instead used split
  frontend/src/lib/slideOverItems/SchemaBuilder.svelte
  frontend/src/utils/frameBuilder.ts
Labels: bug
